### ISSUE TITLE
Move YAML files into separate repository

### ISSUE THREAD

**Issue by HactarCE** [porpoiseless/ithkuil_freedoc#5]
I think that the YAML files should be moved to a separate repository, which can then be included as a submodule in this one and others, without carrying the unnecessary weight of images and documentation generation. [NILDB](https://github.com/HactarCE/NILDB) is a repository I created a while ago for this exact purpose. I can convert what's already there (phonology and some of the roots) into YAML as well.

**Comment by porpoiseless** [comment]
Sounds good to put raw yaml in its own repo, it will make things less messy. I think docgen should still go in the freedoc or something similar--the goal is to compile what amounts to A Grammar of TNIL, including both reference material and tutorials/high level overviews.

**Comment by porpoiseless** [comment]
Good call; it is done. YAML contributions will be done in a fork of NILDB.
